#!/bin/bash
#SBATCH -p gpi.develop             # Partition to submit to
#SBATCH --mem=4G      # Max CPU Memory
#SBATCH --gres=gpu:1
#SBATCH -o jobs/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e jobs/%x_%u_%j.err # File to which STDERR will be written
python setup.py build_ext  develop
