model:
  channels: 32
  num_blocks: 7
  semantic_classes: 2
  instance_classes: 2
  sem2ins_classes: [0]
  semantic_only: False
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.5
    radius: 0.006
    mean_active: 60
    class_numpoint_mean: [-1., -1.]
    npoint_thr: 0.1  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: [0]
  instance_voxel_cfg:
    scale: 50
    spatial_shape: 10
  train_cfg:
    size_feats: 35
    full_feats_size: False
    max_proposal_num: 500
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: True
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 500
  # fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear']
  # fixed_modules: ['input_conv', 'unet', 'output_layer', 'semantic_linear', 'offset_linear',
  #                 'tiny_unet', 'cls_linear', 'mask_linear', 'iou_score_linear']
  fixed_modules: []

data:
  train:
    type: 'apples_size'
    data_root: 'dataset/applesTFM/train_all'
    size_path: 'dataset/applesTFM/all_apples_final.csv'
    prefix: 'tree'
    suffix: '_segmented.las'
    repeat: 6
    training: True
    voxel_cfg:
      scale: 100
      spatial_shape: [64, 256]
      max_npoint: 300000
      min_npoint: 3000
  test:
    type: 'apples_size'
    data_root: 'dataset/applesTFM/test_all'
    size_path: 'dataset/applesTFM/all_apples_final.csv'
    prefix: 'tree'
    suffix: '_segmented.las'
    training: False
    voxel_cfg:
      scale: 100
      spatial_shape: [64, 256]
      max_npoint: 300000
      min_npoint: 3000


dataloader:
  train:
    batch_size: 3
    num_workers: 1
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.005

save_cfg:
  semantic: False
  offset: False
  instance: True

fp16: False
epochs: 30
step_epoch: 0
save_freq: 10
pretrain: ''
# pretrain: './hais_ckpt_spconv2.pth'
pretrain: './work_dirs/instance/FrzPtr77_2outs_radius0004_lr001_Adam_scr05_sclInst50_shapeIns7/best_model.pth'
# work_dir: 'work_dirs/size/aux_full'
work_dir: 'work_dirs/all/ptr90_inst50_10_sem100_Adam0005'